### PR TITLE
Added a link to a mirror in Tor

### PR DESCRIPTION
**Pull request by httsmvkcom**

### CODE REVIEW

**Comment by httsmvkcom** [comment]
изображение
http://duinoyliedtvs4zp7wtz2o7uqmv4tfcyvdlclbwr3zbez2hxwolry7ad.onion/

**Review by Maxi1357 — APPROVED** [review]
Nice. Revox Should add this

**Comment by IdotMaster1** [comment]
this is cool

**Review by IdotMaster1 — APPROVED** [review]
i approve of this

**Comment by revoxhere** [comment]
thanks and sorry for the wait, i explained it on discord

**Pull request merged**
