### PR TITLE
Added a new server IP

### PR DESCRIPTION
**Pull request by httsmvkcom**
#DUCOSTAYALIVE

### CODE REVIEW

**Comment by Bilaboz** [comment]
We switched back to the first provider, so the IP gonna change again soon

**Comment by httsmvkcom** [comment]
Wouldn't it be better to get the data from GitHub instead of directly from the server?

**Comment by Bilaboz** [comment]
yes it's done with https://github.com/revoxhere/duino-coin/blob/gh-pages/serverip.txt

**Comment by httsmvkcom** [comment]
I think it's better that way
Let @revoxhere decide how best to proceed

**Comment by revoxhere** [comment]
Oh yes, I think I'll make it grab the ip from github file later, closing for now

**Pull request closed without merging**
